name: Docker Images Builder

on:
  push:
    branches: [ master ]

env:
  DH_IMAGE_BASE_NAME: alvrme/alpine-android-base
  DH_IMAGE_NAME: alvrme/alpine-android
  GHCR_IMAGE_BASE_NAME: alvr/alpine-android-base
  GHCR_IMAGE_NAME: alvr/alpine-android
  QUAY_IMAGE_BASE_NAME: alvr/alpine-android-base
  QUAY_IMAGE_NAME: alvr/alpine-android
  DOCKERHUB_USER: alvrme
  QUAY_USER: alvr

jobs:
  build_base_image_jdk8:
    name: Build Base Image JDK8
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android Base Image JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-base
          file: ./android-base/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_BASE_NAME }}:jdk8
            ${{ env.DH_IMAGE_BASE_NAME }}:latest
            ${{ env.DH_IMAGE_BASE_NAME }}:latest-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:jdk8
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:latest
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:latest-jdk8
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:jdk8
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:latest
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:latest-jdk8

  build_base_image_jdk11:
    name: Build Base Image JDK11
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android Base Image JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-base
          file: ./android-base/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_BASE_NAME }}:jdk11
            ${{ env.DH_IMAGE_BASE_NAME }}:latest-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:jdk11
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:latest-jdk11
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:jdk11
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:latest-jdk11

  build_images_jdk8:
    name: Build Images JDK8
    needs: [build_base_image_jdk8]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android API 21 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-21
          file: ./android-21/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-21
            ${{ env.DH_IMAGE_NAME }}:android-21-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-21
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-21-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-21
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-21-jdk8

      - name: Build Android API 22 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-22
          file: ./android-22/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-22
            ${{ env.DH_IMAGE_NAME }}:android-22-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-22
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-22-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-22
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-22-jdk8

      - name: Build Android API 23 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-23
          file: ./android-23/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-23
            ${{ env.DH_IMAGE_NAME }}:android-23-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-23
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-23-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-23
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-23-jdk8

      - name: Build Android API 24 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-24
          file: ./android-24/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-24
            ${{ env.DH_IMAGE_NAME }}:android-24-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-24
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-24-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-24
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-24-jdk8

      - name: Build Android API 25 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-25
          file: ./android-25/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-25
            ${{ env.DH_IMAGE_NAME }}:android-25-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-25
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-25-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-25
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-25-jdk8

      - name: Build Android API 26 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-26
          file: ./android-26/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-26
            ${{ env.DH_IMAGE_NAME }}:android-26-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-26
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-26-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-26
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-26-jdk8

      - name: Build Android API 27 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-27
          file: ./android-27/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-27
            ${{ env.DH_IMAGE_NAME }}:android-27-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-27
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-27-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-27
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-27-jdk8

      - name: Build Android API 28 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-28
          file: ./android-28/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-28
            ${{ env.DH_IMAGE_NAME }}:android-28-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-28
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-28-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-28
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-28-jdk8

      - name: Build Android API 29 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-29
          file: ./android-29/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-29
            ${{ env.DH_IMAGE_NAME }}:android-29-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-29
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-29-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-29
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-29-jdk8

      - name: Build Android API 30 JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-30
          file: ./android-30/Dockerfile.jdk8
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-30
            ${{ env.DH_IMAGE_NAME }}:android-30-jdk8
            ${{ env.DH_IMAGE_NAME }}:latest
            ${{ env.DH_IMAGE_NAME }}:latest-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-30
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-30-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-30
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-30-jdk8
            quay.io/${{ env.QUAY_IMAGE_NAME }}:latest
            quay.io/${{ env.QUAY_IMAGE_NAME }}:latest-jdk8

  build_images_jdk11:
    name: Build Images JDK11
    needs: [build_base_image_jdk11]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android API 21 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-21
          file: ./android-21/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-21-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-21-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-21-jdk11

      - name: Build Android API 22 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-22
          file: ./android-22/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-22-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-22-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-22-jdk11

      - name: Build Android API 23 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-23
          file: ./android-23/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-23-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-23-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-23-jdk11

      - name: Build Android API 24 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-24
          file: ./android-24/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-24-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-24-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-24-jdk11

      - name: Build Android API 25 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-25
          file: ./android-25/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-25-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-25-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-25-jdk11

      - name: Build Android API 26 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-26
          file: ./android-26/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-26-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-26-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-26-jdk11

      - name: Build Android API 27 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-27
          file: ./android-27/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-27-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-27-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-27-jdk11

      - name: Build Android API 28 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-28
          file: ./android-28/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-28-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-28-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-28-jdk11

      - name: Build Android API 29 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-29
          file: ./android-29/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-29-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-29-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-29-jdk11

      - name: Build Android API 30 JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-30
          file: ./android-30/Dockerfile.jdk11
          push: true
          tags: |
            ${{ env.DH_IMAGE_NAME }}:android-30-jdk11
            ${{ env.DH_IMAGE_NAME }}:latest-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:android-30-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:android-30-jdk11
            quay.io/${{ env.QUAY_IMAGE_NAME }}:latest-jdk11
