name: Docker Images Builder

on:
  push:
    branches:
      - "!*"
    tags:
      - v*

env:
  DH_IMAGE_BASE_NAME: alvrme/alpine-android-base
  DH_IMAGE_NAME: alvrme/alpine-android
  GHCR_IMAGE_BASE_NAME: alvr/alpine-android-base
  GHCR_IMAGE_NAME: alvr/alpine-android
  QUAY_IMAGE_BASE_NAME: alvr/alpine-android-base
  QUAY_IMAGE_NAME: alvr/alpine-android
  DOCKERHUB_USER: alvrme
  QUAY_USER: alvr
  LATEST_STABLE_API: 30

jobs:
  build_base_image_jdk8:
    name: Build Base Image JDK8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android Base Image JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-base
          file: ./android-base/jdk8.Dockerfile
          push: true
          tags: |
            ${{ env.DH_IMAGE_BASE_NAME }}:jdk8
            ${{ env.DH_IMAGE_BASE_NAME }}:latest
            ${{ env.DH_IMAGE_BASE_NAME }}:latest-jdk8
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:jdk8
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:latest
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:latest-jdk8
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:jdk8
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:latest
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:latest-jdk8

  build_base_image_jdk11:
    name: Build Base Image JDK11
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android Base Image JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-base
          file: ./android-base/jdk11.Dockerfile
          push: true
          tags: |
            ${{ env.DH_IMAGE_BASE_NAME }}:jdk11
            ${{ env.DH_IMAGE_BASE_NAME }}:latest-jdk11
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:jdk11
            ghcr.io/${{ env.GHCR_IMAGE_BASE_NAME }}:latest-jdk11
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:jdk11
            quay.io/${{ env.QUAY_IMAGE_BASE_NAME }}:latest-jdk11

  build_images_jdk8:
    name: Build Images JDK8
    needs: [build_base_image_jdk8]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android-api:
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag version
        id: tag_version
        uses: battila7/get-version-action@v2

      - name: Tags
        run: |
          TAGS="android-${{ matrix.android-api }}"
          TAGS="$TAGS,android-${{ matrix.android-api }}-jdk8"
          TAGS="$TAGS,android-${{ matrix.android-api }}-jdk8-${{ steps.tag_version.outputs.version }}"
          if [ "${{ matrix.android-api }}" = "${{ env.LATEST_STABLE_API }}" ]; then
            TAGS="$TAGS,latest"
            TAGS="$TAGS,latest-jdk8"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DH_IMAGE_NAME }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}
            quay.io/${{ env.QUAY_IMAGE_NAME }}
          tag-custom: ${{ env.TAGS }}
          tag-custom-only: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android API ${{ matrix.android-api }} JDK8
        uses: docker/build-push-action@v2
        with:
          context: ./android-${{ matrix.android-api }}
          file: ./android-${{ matrix.android-api }}/jdk8.Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

  build_images_jdk11:
    name: Build Images JDK11
    needs: [build_base_image_jdk11]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android-api:
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag version
        id: tag_version
        uses: battila7/get-version-action@v2

      - name: Tags
        run: |
          TAGS="android-${{ matrix.android-api }}-jdk11"
          TAGS="$TAGS,android-${{ matrix.android-api }}-jdk11-${{ steps.tag_version.outputs.version }}"
          if [ "${{ matrix.android-api }}" = "${{ env.LATEST_STABLE_API }}" ]; then
            TAGS="$TAGS,latest-jdk11"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DH_IMAGE_NAME }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}
            quay.io/${{ env.QUAY_IMAGE_NAME }}
          tag-custom: ${{ env.TAGS }}
          tag-custom-only: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Android API ${{ matrix.android-api }} JDK11
        uses: docker/build-push-action@v2
        with:
          context: ./android-${{ matrix.android-api }}
          file: ./android-${{ matrix.android-api }}/jdk11.Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
